name: Full-Stack-Banking-Application

on: 
  push:
    branches: ['main']

jobs: 
  build:
  
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout the repo    
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: mahmoudbraima/Full-Stack-Banking-Application
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
  deploy:
      needs: build
      
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout files    
          uses: actions/checkout@v4

        - name: Get tag name
          uses: olegtarasov/get-tag@v2
          
        - name: Install doctl
          uses: digitalocean/action-doctl@v2
          with:
           token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
           
        - name: Provision Droplet and deploy container
          run: doctl compute droplet create "banking_app" \
            --image docker-18-04 \
            --size s-2vcpu-2gb \
            --region sf02 \
            --user-data-file deploy.sh \
            --wait
