name: Full-Stack-Banking-Application

on: 
  push:
    branches: ['main']

jobs: 
  build:
  
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout the repo    
        uses: actions/checkout@v4

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: mahmoudbraima/Full-Stack-Banking-Application
          tag_with_ref: true
          tag_with_sha: true
  
  deploy:
      needs: build
      
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout files    
          uses: actions/checkout@v4

        - name: Get tag name
          uses: olegtarasov/get-tag@v2
          
        - name: Install doctl
          uses: digitalocean/action-doctl@v2
          with:
           token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
           
        - name: Provision Droplet and deploy container
          run: doctl compute droplet create \
              --image ubuntu-23-10-x64 \
              --size s-1vcpu-1gb \
              --region sfo2 \
              ubuntu-s-1vcpu-1gb-sfo2-01
      
  
